[package]
name        = "rskit-storage-s3"
description = "Amazon S3 and S3-compatible (MinIO, LocalStack) storage backend for rskit-storage"
version = "0.2.0-alpha.5"
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation          = "https://docs.rs/rskit-storage-s3"
readme                 = "README.md"
categories             = ["filesystem", "asynchronous", "web-programming"]
keywords               = ["s3", "minio", "storage", "async", "file"]

[dependencies]
rskit-errors.workspace = true
rskit-storage.workspace = true
rskit-util.workspace = true
aws-sdk-s3 = { workspace = true }
async-trait  = { workspace = true }
bytes        = { workspace = true }
chrono       = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
tracing      = { workspace = true }
tokio        = { workspace = true, features = ["sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "full"] }
aws-smithy-http-client = { workspace = true }
aws-smithy-types = { workspace = true }
http = { workspace = true }
