[package]
name        = "rskit-storage-gcs"
description = "Google Cloud Storage backend for rskit-storage"
version = "0.1.0-alpha.1"
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation          = "https://docs.rs/rskit-storage-gcs"
readme                 = "README.md"
categories             = ["filesystem", "asynchronous", "web-programming"]
keywords               = ["gcs", "google-cloud", "storage", "async", "file"]

[lints]
workspace = true

[dependencies]
rskit-errors.workspace = true
rskit-storage.workspace = true
async-trait   = { workspace = true }
bytes         = { workspace = true }
chrono        = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
google-cloud-storage = { workspace = true }
google-cloud-auth = { workspace = true }
rustls = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio      = { workspace = true, features = ["test-util", "full"] }
google-cloud-gax = { workspace = true }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
