[package]
name        = "rskit-storage"
description = "File I/O, local storage, temp files, MIME detection, and storage backend traits"
version = "0.2.0-alpha.3"
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation          = "https://docs.rs/rskit-storage"
readme                 = "README.md"
categories             = ["filesystem", "asynchronous"]
keywords               = ["file", "storage", "async", "streaming"]

[dependencies]
# External
tokio           = { workspace = true, features = ["fs", "io-util"] }
bytes           = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
tracing         = { workspace = true }
chrono          = { workspace = true }
async-trait     = { workspace = true }
futures         = { workspace = true }
futures-util    = { workspace = true }
tempfile = { workspace = true }
mime_guess = { workspace = true }
infer = { workspace = true }

# Internal
rskit-errors = { workspace = true }
rskit-fs = { workspace = true, features = ["async"] }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "full"] }
image = { workspace = true }
bytes = { workspace = true }
insta = { workspace = true }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
