[package]
name        = "rskit-storage"
description = "File I/O, local storage, temp files, MIME detection, and storage backend traits"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation          = "https://docs.rs/rskit-storage"
readme                 = "README.md"
categories             = ["filesystem", "asynchronous"]
keywords               = ["file", "storage", "async", "streaming"]

[dependencies]
# External
tokio           = { workspace = true, features = ["fs", "io-util"] }
bytes           = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
tracing         = { workspace = true }
chrono          = { workspace = true }
async-trait     = { workspace = true }
futures         = { workspace = true }
futures-util    = { workspace = true }
pin-project-lite = { workspace = true }
tempfile        = "3"
mime_guess      = "2"
infer           = "0.19"

# Internal
rskit-errors    = { version = "0.1.0", path = "../rskit-errors" }
rskit-fs        = { version = "0.1.0", path = "../rskit-fs" }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "full"] }
image = "0.25"
bytes = { workspace = true }
insta = { workspace = true }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
