[package]
name        = "rskit-validation"
description = "Fluent field-level validator that collects errors and converts to AppError"
version.workspace     = true
edition.workspace     = true
license.workspace     = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation = "https://docs.rs/rskit-validation"
readme = "README.md"
categories = ["development-tools"]
keywords   = ["validation", "validator"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# External
serde        = { workspace = true }
serde_json   = { workspace = true }
regex        = "1"
uuid         = { workspace = true }
chrono       = { workspace = true }
validator = { workspace = true }

# Internal
rskit-errors = { version = "0.1.0-alpha.1", path = "../rskit-errors" }
