[package]
name        = "rskit-messaging"
description = "Message broker abstractions, registry, middleware, and in-memory backend"
version.workspace     = true
edition.workspace     = true
license.workspace     = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation = "https://docs.rs/rskit-messaging"
readme = "README.md"
categories = ["asynchronous"]
keywords   = ["messaging", "broker", "producer", "consumer"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
provider-bridge = ["dep:rskit-provider"]
bridges = ["provider-bridge"]

[dependencies]
rskit-errors      = { path = "../rskit-errors" }
rskit-bootstrap   = { path = "../rskit-bootstrap" }
rskit-resilience  = { path = "../rskit-resilience" }
rskit-provider  = { path = "../rskit-provider", optional = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
async-trait     = { workspace = true }
async-stream    = { workspace = true }
tokio           = { workspace = true }
tokio-util      = { workspace = true }
tokio-stream    = { workspace = true }
futures         = { workspace = true }
tracing         = { workspace = true }
parking_lot     = { workspace = true }
chrono          = { workspace = true }
uuid            = { workspace = true }

