[package]
name        = "rskit-messaging"
description = "Message broker abstractions, registry, middleware, and in-memory adapter"
version = "0.2.0-alpha.4"
edition.workspace     = true
license.workspace     = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation = "https://docs.rs/rskit-messaging"
readme = "README.md"
categories = ["asynchronous"]
keywords   = ["messaging", "broker", "producer", "consumer"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
provider-bridge = ["dep:rskit-provider"]
bridges = ["provider-bridge"]

[dependencies]
# External
serde           = { workspace = true }
serde_json      = { workspace = true }
async-trait     = { workspace = true }
async-stream    = { workspace = true }
tokio           = { workspace = true }
futures         = { workspace = true }
tracing         = { workspace = true }
parking_lot     = { workspace = true }
chrono          = { workspace = true }
uuid            = { workspace = true }

# Internal
rskit-errors = { workspace = true }
rskit-resilience = { workspace = true }
rskit-stream = { workspace = true }
rskit-provider = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
