[package]
name        = "rskit-cache-redis"
description = "Redis adapter for rskit-cache"
version = "0.1.0-alpha.1"
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation          = "https://docs.rs/rskit-cache-redis"
readme                 = "README.md"
categories             = ["caching"]
keywords               = ["cache", "redis", "adapter"]

[dependencies]
async-trait = { workspace = true }
redis = { workspace = true, features = ["tokio-comp", "connection-manager"] }
serde       = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }

rskit-cache  = { workspace = true }
rskit-errors = { workspace = true }
rskit-util   = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
