[package]
name        = "rskit-cache-redis"
description = "Redis adapter for rskit-cache"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation          = "https://docs.rs/rskit-cache-redis"
readme                 = "README.md"
categories             = ["caching"]
keywords               = ["cache", "redis", "adapter"]

[dependencies]
async-trait = { workspace = true }
redis       = { version = "1.2", features = ["tokio-comp", "connection-manager"] }
serde       = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }

rskit-cache  = { workspace = true }
rskit-errors = { workspace = true }
rskit-util   = { workspace = true }
