[package]
name        = "rskit-dag"
description = "DAG task orchestrator with parallel execution"
version = "0.2.0-alpha.2"
edition.workspace     = true
license.workspace     = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation = "https://docs.rs/rskit-dag"
readme = "README.md"
categories = ["concurrency"]
keywords   = ["dag", "orchestration", "pipeline"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# External
serde_json   = { workspace = true }
serde        = { workspace = true }
async-trait  = { workspace = true }
tokio        = { workspace = true }
tracing      = { workspace = true }
tokio-util   = { workspace = true }
parking_lot  = { workspace = true }

# Internal
rskit-errors = { workspace = true }
rskit-provider = { workspace = true }

[lints]
workspace = true
