[package]
name        = "rskit-observability"
description = "OpenTelemetry tracing, metrics, and context propagation"
version = "0.2.0-alpha.3"
edition.workspace     = true
license.workspace     = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation = "https://docs.rs/rskit-observability"
readme = "README.md"
categories = ["development-tools::profiling"]
keywords   = ["opentelemetry", "tracing", "metrics", "prometheus"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
otlp = ["dep:opentelemetry-otlp"]

[dependencies]
# External
serde           = { workspace = true }
tokio           = { workspace = true }
tracing         = { workspace = true }
parking_lot     = { workspace = true }
opentelemetry            = { workspace = true }
opentelemetry_sdk        = { workspace = true }
opentelemetry-otlp       = { workspace = true, optional = true }
tracing-opentelemetry    = { workspace = true }
http            = { workspace = true }

# Internal
rskit-errors = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
