[package]
name        = "rskit-cache"
description = "Cache abstraction with explicit store registration and local adapters"
version.workspace     = true
edition.workspace     = true
license.workspace     = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation = "https://docs.rs/rskit-cache"
readme = "README.md"
categories = ["caching"]
keywords   = ["cache", "memory", "store"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
fs = ["dep:blake3", "dep:rskit-fs"]

[dependencies]
# External
serde           = { workspace = true }
serde_json      = { workspace = true }
async-trait     = { workspace = true }
tokio           = { workspace = true }
tracing         = { workspace = true }
parking_lot     = { workspace = true }
blake3          = { version = "1", optional = true }

# Internal
rskit-errors    = { version = "0.1.0-alpha.1", path = "../rskit-errors" }
rskit-fs        = { version = "0.1.0-alpha.1", path = "../rskit-fs", optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
