#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)"
export ROOT_DIR

python3 <<'PY'
from __future__ import annotations

import os
import tomllib
from pathlib import Path

DOMAIN_EMOJI = {
    "core": "🧱",
    "patterns": "🔧",
    "crosscutting": "🔄",
    "composition": "🏗️",
    "transport": "🌐",
    "auth": "🔑",
    "data": "💾",
    "ai": "🧠",
    "media": "🎬",
    "infra": "⚙️",
}
DOMAIN_ORDER = [
    "core",
    "patterns",
    "crosscutting",
    "composition",
    "transport",
    "auth",
    "data",
    "ai",
    "media",
    "infra",
]
DOMAIN_TITLES = {
    "core": "Core",
    "patterns": "Patterns",
    "crosscutting": "Cross-cutting",
    "composition": "Composition",
    "transport": "Transport",
    "auth": "Auth",
    "data": "Data",
    "ai": "AI",
    "media": "Media",
    "infra": "Infra",
}

root_dir = Path(os.environ["ROOT_DIR"])
domains_path = root_dir / "domains.toml"
docs_dir = root_dir / "docs"
output_path = docs_dir / "MODULE-INDEX.md"

with domains_path.open("rb") as file:
    data = tomllib.load(file)

domains = data.get("domains", {})
docs_dir.mkdir(parents=True, exist_ok=True)

lines = [
    "# Module Index by Domain",
    "",
    "<!-- Auto-generated by scripts/generate-module-index.sh — do not edit manually -->",
    "",
]

ordered_domains = [domain for domain in DOMAIN_ORDER if domain in domains]
ordered_domains.extend(domain for domain in domains if domain not in DOMAIN_ORDER)

for domain in ordered_domains:
    modules = domains[domain].get("modules", [])
    emoji = DOMAIN_EMOJI.get(domain, "📦")
    title = DOMAIN_TITLES.get(domain, domain.replace("-", " ").title())

    lines.append(f"## {emoji} {title}  (`make check-{domain}`)")
    lines.append(" · ".join(modules))
    lines.append("")

output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
print(f"Generated {output_path}")
PY
