[package]
name        = "agent-demo"
version.workspace     = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
publish     = false

[dependencies]
rskit = { workspace = true, features = ["cli", "media-image"] }

tokio       = { workspace = true, features = ["full"] }
tokio-util  = { workspace = true }
indicatif   = { workspace = true }
async-trait = { workspace = true }
tracing     = { workspace = true }
uuid        = { version = "1", features = ["v4"] }
chrono      = { workspace = true }
