[package]
name        = "rskit-config"
description = "Adapter-oriented configuration loading with validation"
version.workspace     = true
edition.workspace     = true
license.workspace     = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true
documentation = "https://docs.rs/rskit-config"
readme = "README.md"
categories = ["config"]
keywords   = ["config", "toml", "env", "settings"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# External
serde        = { workspace = true }
config       = { workspace = true }
dotenvy      = { workspace = true }
validator = { workspace = true }
tracing      = { workspace = true }

# Internal
rskit-errors = { version = "0.1.0", path = "../rskit-errors" }
rskit-version = { version = "0.1.0", path = "../rskit-version" }
rskit-fs = { version = "0.1.0", path = "../rskit-fs", default-features = false }
rskit-util = { version = "0.1.0", path = "../rskit-util" }
rskit-validation = { version = "0.1.0", path = "../rskit-validation" }

[dev-dependencies]
parking_lot = { workspace = true }
serde_json   = { workspace = true }
tempfile    = "3"
tokio       = { workspace = true }
