[package]
name    = "media-demo"
version.workspace     = true
edition.workspace     = true
license.workspace     = true
rust-version.workspace = true
publish               = false

[dependencies]
rskit = { workspace = true, features = ["media-full"] }
tokio = { workspace = true, features = ["full"] }
