[package]
name = "rskit-git"
version = "0.2.0-alpha.1"
edition.workspace = true
description = "Composable git repository interfaces backed by libgit2"
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/rskit-git"
readme = "README.md"
categories = ["development-tools"]
keywords = ["git", "repository", "diff", "version-control"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
testutil = ["dep:tempfile"]

[dependencies]
# External
git2 = { workspace = true, features = ["https", "ssh"] }
thiserror = { workspace = true }
tempfile = { workspace = true, optional = true }

# Internal
rskit-errors = { workspace = true }
rskit-fs = { workspace = true }
rskit-process = { workspace = true }

[dev-dependencies]
rskit-testutil = { workspace = true }
tempfile = { workspace = true }
